"""0_initial_migration

Revision ID: 15be00f17222
Revises:
Create Date: 2023-10-11 13:55:15.158866

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "15be00f17222"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=256), nullable=False),
        sa.Column("registration_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("salesforce_id", sa.String(length=256), nullable=True),
        sa.Column("registration_platform", sa.String(length=256), nullable=False),
        sa.Column("created_by", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(
        op.f("ix_customer_registration_date"), "customer", ["registration_date"], unique=False
    )
    op.create_index(op.f("ix_customer_uid"), "customer", ["uid"], unique=False)
    op.create_table(
        "event_bus_events_event",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("topic_name", sa.String(length=254), nullable=False),
        sa.Column("producer", sa.String(length=254), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_bus_events_event_topic_name"),
        "event_bus_events_event",
        ["topic_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_event_bus_events_event_topic_name"), table_name="event_bus_events_event")
    op.drop_table("event_bus_events_event")
    op.drop_index(op.f("ix_customer_uid"), table_name="customer")
    op.drop_index(op.f("ix_customer_registration_date"), table_name="customer")
    op.drop_table("customer")
    # ### end Alembic commands ###
